Repository poseidonos/poseidonos, pull requests merged in 2022-09, with the labels that each got.

#316 [AWIBOF-6828] add telemetry metric for volume
  doc/development/telemetry/ID_RULES.md
  doc/development/telemetry/METRICS.md
  src/telemetry/telemetry_air/telemetry_air_delegator.h
  src/telemetry/telemetry_id.h
  src/volume/volume_base.h
  src/volume/volume_manager.cpp
  src/volume/volume_manager.h
Labels: telemetry

#312 [AWIBOF-6910] Reduce time to generate event table
  src/logger/pos_event_id.cpp
Labels: log, telemetry

#314 [AWIBOF-6897] Galois field table caching to improve RAID6 rebuild performance
  src/array/ft/raid6.cpp
  src/array/ft/raid6.h
  src/array/partition/stripe_partition.cpp
  src/include/array_config.h
  test/regression/fault_tolerance_ci_test_for_raid6.sh
Labels: SRM

#321 [AWIBOF-6940] Fix IO System Level Test script error due to changed cl…
  test/system/io_path/common_test_lib.py
  test/system/io_path/nvmf_common.py
  test/system/io_path/nvmf_test.py
Labels: CLI, IOPath

#317 [AWIBOF-6916] Modify operation of considering meta scheduler setting
  config/pos_multi_array_normal.conf
  src/event/pos_event.yaml
  src/metafs/config/metafs_config_manager.cpp
  src/metafs/config/metafs_config_manager.h
  src/metafs/include/metafs_service.h
  src/metafs/metafs_service.cpp
  src/metafs/mim/metafs_io_scheduler.cpp
  src/metafs/mim/metafs_io_scheduler.h
  test/unit-tests/metafs/config/metafs_config_manager_mock.h
  test/unit-tests/metafs/config/metafs_config_manager_test.cpp
  test/unit-tests/metafs/include/metafs_service_test.cpp
Labels: Meta

#326 [AWIBOF-6995] Delete unusing function
  src/qos/monitoring_manager_array.cpp
  src/qos/monitoring_manager_array.h
  test/unit-tests/qos/monitoring_manager_array_test.cpp
Labels: IOPath

#328 [AWIBOF-6942] Add reactor only config for Physical Machine's CI test
  config/ibofos_for_psd_ci.conf
  config/ibofos_for_psd_ci_wt.conf
  config/pos_multi_array_normal.conf
Labels: config

#336 [AWIBOF-7017] Fix memory leaks of metafs
  src/metafs/config/metafs_config_manager.cpp
  src/metafs/include/metafs_service.h
  src/metafs/metafs_service.cpp
  test/integration-tests/metafs/lib/metafs_test_fixture.cpp
  test/unit-tests/metafs/include/metafs_service_test.cpp
Labels: Meta

#339 [AWIBOF-6973] Add target IP address to array and CREATEVOLUME command
  doc/guides/cli/pos_railroad.html
  doc/guides/cli/poseidonos-cli_array_mount.md
  doc/troubleshooting/events.md
  proto/cli.proto
  proto/generated/cpp/cli.pb.cc
  proto/generated/cpp/cli.pb.h
  src/array/array.cpp
  src/array/array.h
  src/array_components/array_components.cpp
  src/array_components/array_components.h
  src/array_mgmt/array_manager.cpp
  src/array_mgmt/array_manager.h
  src/array_mgmt/interface/i_array_mgmt.h
  src/cli/command_processor.cpp
  src/cli/command_processor.h
  src/event/pos_event.yaml
  test/unit-tests/array/array_mock.h
  test/unit-tests/array_components/array_components_mock.h
  test/unit-tests/array_mgmt/array_manager_mock.h
  test/unit-tests/array_mgmt/interface/i_array_mgmt_mock.h
  tool/cli/cmd/arraycmds/mount_array.go
  tool/cli/cmd/pos_cli_syntax.ebnf
Labels: CLI

#342 [AWIBOF-6942] Reactor Wrapping IO is moved from uram internal to device manager
  src/device/base/ublock_device.cpp
  src/device/base/ublock_device.h
  src/device/device_manager.cpp
  src/device/uram/uram.cpp
  src/device/uram/uram.h
  test/unit-tests/device/base/ublock_device_mock.h
  test/unit-tests/device/uram/uram_mock.h
Labels: IOPath

#344 [AWIBOF-7028] Disable omitempty when marshalling protobuf to json
  tool/cli/cmd/displaymgr/display_response.go
Labels: bug, CLI

#341 [AWIBOF-7026] update learning_configuration.md for write_through and …
  doc/guides/getting_started/learning_configuration.md
Labels: documentation

#354 [AWIBOF-7050] Change DELETE/UNMOUNTVOLUME commands to gRPC
  doc/guides/cli/poseidonos-cli_volume_unmount.md
  proto/cli.proto
  proto/generated/cpp/cli.grpc.pb.cc
  proto/generated/cpp/cli.grpc.pb.h
  proto/generated/cpp/cli.pb.cc
  proto/generated/cpp/cli.pb.h
  src/cli/command_processor.cpp
  src/cli/command_processor.h
  src/cli/grpc_cli_server.cpp
  tool/cli/cmd/grpcmgr/grpcmgr.go
  tool/cli/cmd/volumecmds/delete_volume.go
  tool/cli/cmd/volumecmds/unmount_volume.go
Labels: CLI

#355 [AWIBOF-7003] Deploy AIR v0.8.5-beta
  lib/CMakeLists.txt
Labels: AIR

#357 [AWIBOF-7054] Not display start message when --json-res flag is specified
  tool/cli/cmd/systemcmds/start_system.go
Labels: bug, CLI

#356 [AWIBOF-7053] Fix memory leak by CLI-related modules
  src/cli/cli_server.cpp
  src/main/poseidonos.cpp
Labels: bug

#359 [AWIBOF-7047] modified flush command handling.
  src/allocator/context_manager/context_manager.cpp
  src/allocator/context_manager/context_manager.h
  src/allocator/i_context_manager.h
  src/journal_manager/journal_manager.cpp
  test/integration-tests/journal/fake/i_context_manager_mock.h
  test/unit-tests/allocator/context_manager/context_manager_mock.h
  test/unit-tests/allocator/i_context_manager_mock.h
  test/unit-tests/journal_manager/journal_manager_test.cpp
Labels: Meta

#360 [AWIBOF-6686] add pending io metric
  config/air.cfg
  config/air_ci.cfg
  doc/development/telemetry/METRICS.md
  src/debug/debug_info.cpp
  src/debug/debug_info.h
  src/event/pos_event.yaml
  src/event_scheduler/callback.cpp
  src/event_scheduler/callback.h
  src/event_scheduler/callback_type.h
  src/event_scheduler/io_timeout_checker.cpp
  src/event_scheduler/io_timeout_checker.h
  src/event_scheduler/publish_pending_io.cpp
  src/event_scheduler/publish_pending_io.h
  src/io/frontend_io/write_submission.cpp
  src/main/poseidonos.cpp
  src/telemetry/telemetry_air/telemetry_air_delegator.cpp
  src/telemetry/telemetry_air/telemetry_air_delegator.h
  src/telemetry/telemetry_id.h
Labels: telemetry, IOPath

#362 [AWIBOF-7060] add shutdown process at Replicator Volume Subscriber
  src/event/pos_event.yaml
  src/pos_replicator/posreplicator_manager.cpp
  src/pos_replicator/replicator_volume_subscriber.cpp
Labels: IOPath, 2node-HA

#343 [AWIBOF-7021] Remove memory leak of meta modules
  src/journal_manager/journal_manager.cpp
  src/metafs/include/meta_file_context.h
  src/metafs/mai/metafs_file_control_api.cpp
  src/metafs/mai/metafs_wbt_api.cpp
  test/integration-tests/allocator/context_manager_integration_test.cpp
  test/unit-tests/metafs/mai/metafs_io_api_test.cpp
  test/unit-tests/metafs/mai/metafs_wbt_api_test.cpp
  test/unit-tests/metafs/mim/metafs_io_request_test.cpp
  test/unit-tests/metafs/mim/metafs_io_scheduler_test.cpp
Labels: Meta

#367 [AWIBOF-7066] Fix raid6 multi-device CI test
  test/regression/fault_tolerance_ci_test_for_raid6_multi_device.sh
Labels: SRM

#370 [AWIBOF-7071] bugfix for memory leak
  src/main/poseidonos.cpp
Labels: telemetry, IOPath

#371 Bugfix/awibof 7071 bug fix singleton memory leak
  src/main/poseidonos.cpp
Labels: telemetry, IOPath

#374 [AWIBOF-7075] Remove debug event logs from TelemetryPublisher
  src/telemetry/telemetry_client/telemetry_publisher.cpp
Labels: log

#377 [AWIBOF-7066] Update RAID6 CI test
  test/regression/fault_tolerance_ci_test_for_raid6_multi_device.sh
Labels: SRM

#379 [AWIBOF-6758] Re-try write gc journal when add log fails
  src/event/pos_event.yaml
  src/event_scheduler/callback_type.h
  src/journal_manager/journal_manager.cpp
  src/journal_manager/journal_writer.cpp
  src/journal_manager/journal_writer.h
  src/journal_manager/log_write/gc_log_write.cpp
  src/journal_manager/log_write/gc_log_write.h
  src/journal_manager/log_write/gc_log_write_completed.cpp
  src/journal_manager/log_write/gc_log_write_completed.h
  src/journal_manager/log_write/journal_event_factory.cpp
  src/journal_manager/log_write/journal_event_factory.h
  src/journal_manager/log_write/journal_volume_event_handler.cpp
  src/journal_manager/log_write/journal_volume_event_handler.h
  src/journal_manager/log_write/log_write_request.cpp
  src/journal_manager/log_write/log_write_request.h
  src/journal_manager/log_write/volume_deleted_log_write_callback.cpp
  src/journal_manager/log_write/volume_deleted_log_write_callback.h
  src/journal_manager/log_write/volume_deleted_log_write_request_callback.cpp
  src/journal_manager/log_write/volume_deleted_log_write_request_callback.h
  test/unit-tests/journal_manager/journal_writer_mock.h
  test/unit-tests/journal_manager/journal_writer_test.cpp
  test/unit-tests/journal_manager/log_write/CMakeLists.txt
  test/unit-tests/journal_manager/log_write/gc_log_write_completed_mock.h
  test/unit-tests/journal_manager/log_write/gc_log_write_mock.h
  test/unit-tests/journal_manager/log_write/gc_log_write_test.cpp
  test/unit-tests/journal_manager/log_write/journal_event_factory_mock.h
  test/unit-tests/journal_manager/log_write/journal_event_factory_test.cpp
  test/unit-tests/journal_manager/log_write/journal_volume_event_handler_test.cpp
  test/unit-tests/journal_manager/log_write/log_write_request_mock.h
  test/unit-tests/journal_manager/log_write/log_write_request_test.cpp
  test/unit-tests/journal_manager/log_write/volume_deleted_log_write_callback_mock.h
Labels: Meta

#392 [AWIBOF-7070] Change initialize order of ContextManager
  src/allocator/context_manager/context_manager.h
Labels: Meta

#391 [AWIBOF-7057] reset used variables before executing check point compl…
  src/journal_manager/checkpoint/checkpoint_handler.cpp
Labels: Meta

#399 [AWIBOF-7073] Fix assertion due to new backend event type
  config/air.cfg
  config/air_ci.cfg
  src/cli/command_processor.cpp
  src/cli/update_event_wrr_policy_command.h
  src/device/unvme/unvme_drv.cpp
  src/event_scheduler/backend_event_minimum_policy.cpp
  src/event_scheduler/backend_event_ratio_policy.cpp
Labels: Meta, IOPath

#394 [AWIBOF-7094] Fix to prevent error messages from occurring due to unused callback
  src/metafs/storage/mss.cpp
  src/metafs/storage/mss.h
  src/metafs/storage/pstore/issue_write_event.h
  src/metafs/storage/pstore/mss_on_disk.cpp
  src/metafs/storage/pstore/mss_on_disk.h
  test/unit-tests/metafs/storage/pstore/issue_write_event_test.cpp
Labels: Meta

#406 [AWIBOF-7108] Set telemetry isRunning to false when stopping telemetry
  src/telemetry/telemetry_client/telemetry_client.cpp
Labels: bug, telemetry

#397 [AWIBOF-7102] add thread join, delete for memory leak
  src/event_scheduler/io_timeout_checker.cpp
  src/event_scheduler/io_timeout_checker.h
  src/event_scheduler/publish_pending_io.cpp
  src/event_scheduler/publish_pending_io.h
Labels: telemetry, IOPath

#404 [AWIBOF-7107] fix reset segments state function.
  src/allocator/context_manager/segment_ctx/segment_ctx.cpp
Labels: Meta

#405 [AWIBOF-7100] fixed coverity issue
  src/admin/smart_log_meta_io.cpp
  src/meta_file_intf/rocksdb_metafs_intf.cpp
  src/metafs/mim/metafs_io_scheduler.cpp
  src/telemetry/telemetry_client/pos_metric.cpp
  src/telemetry/telemetry_client/pos_metric.h
  src/telemetry/telemetry_client/telemetry_client.cpp
Labels: Meta, Coverity fixed

#414 Coverity fixed
  src/journal_manager/journal_writer.cpp
Labels: Meta, Coverity fixed

#416 [AWIBOF-7116] Fix RAID6 coverage tests
  src/wbt/update_config_wbt_command.cpp
  test/functional_requirements/fault_tolerance/REBUILD_DETACH_ANOTHER_DEV_DURING_REBUILD_IN_RAID6_ARRAY.py
  test/functional_requirements/fault_tolerance/REBUILD_DETACH_TARGET_DURING_REBUILD_AND_ADD_SPARE.py
  test/functional_requirements/fault_tolerance/REBUILD_IN_RAID10_ARRAY.py
  test/functional_requirements/fault_tolerance/REBUILD_IN_RAID6_ARRAY.py
  test/functional_requirements/fault_tolerance/REBUILD_IN_RAID6_ARRAY_AND_DETACH_TARGET_DURING_REBUILDING.py
  test/functional_requirements/fault_tolerance/REBUILD_IN_RAID6_ARRAY_DURING_IO.py
  test/functional_requirements/fault_tolerance/REBUILD_ONE_DEV_WHEN_TWO_DEVS_FAIL_IN_RAID6_ARRAY_DURING_IO.py
  test/functional_requirements/fault_tolerance/REBUILD_RESUME_TEST_AFTER_SPOR_IN_RAID6_ARRAY.py
  test/functional_requirements/fault_tolerance/REBUILD_TWO_DEVS_CONCURRENTLY_IN_RAID10_ARRAY.py
  test/functional_requirements/fault_tolerance/REBUILD_TWO_DEVS_CONCURRENTLY_IN_RAID6_ARRAY.py
  test/functional_requirements/fault_tolerance/REBUILD_TWO_DEVS_CONCURRENTLY_IN_RAID6_ARRAY_AND_DETACH_TARGET_DURING_REBUILDING.py
  test/functional_requirements/fault_tolerance/REBUILD_TWO_FAULT_DEVS_AND_ONE_SPARE_DEV_IN_RAID6_ARRAY.py
Labels: SRM, testing

#421 [AWIBOF-7125] Fix coverity issue 40585 & 40588
  src/resource_checker/smart_collector.cpp
Labels: Coverity fixed

#417 [AWIBOF-7111] modifiy reset segment condition.
  doc/troubleshooting/events.md
  src/allocator/context_manager/segment_ctx/segment_ctx.cpp
  src/event/pos_event.yaml
  test/unit-tests/allocator/context_manager/segment_ctx/segment_ctx_test.cpp
Labels: Meta

#423 Bugfix/awibof 7112 coverity io path
  src/event_scheduler/io_timeout_checker.cpp
  src/event_scheduler/io_timeout_checker.h
  src/volume/volume_base.cpp
  src/volume/volume_base.h
  src/volume/volume_manager.cpp
Labels: IOPath

#412 [AWIBOF-7115] Change common macro to mfs macro to write log
  src/metafs/storage/pstore/issue_write_event.h
Labels: Meta

#347 [AWIBOF-6988] Change metrics of journal log counts to publish all the log groups
  src/journal_manager/log_write/log_write_handler.cpp
  src/journal_manager/log_write/log_write_handler.h
  test/unit-tests/journal_manager/log_write/log_write_handler_test.cpp
Labels: Meta

#433 [AWIBOF-7134] Fix telemetry selective publication bug
  config/pos.conf
  config/publication_list_default.yaml
  src/master_context/default_configuration.h
  src/telemetry/telemetry_client/telemetry_publisher.cpp
Labels: bug, telemetry
